# Generated by Django 6.0 on 2025-12-10 03:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(default='Dispositivo', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/capturas/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfigAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(help_text='Nome do arquivo ou string de configuração do áudio.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='videos.device', to_field='hostname')),
            ],
            options={
                'verbose_name': 'Áudio do dispositivo',
                'verbose_name_plural': 'Áudios dos dispositivos',
                'ordering': ['hostname', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('hostname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='videos.device', to_field='hostname')),
                ('tempo', models.PositiveIntegerField(default=10, help_text='Tempo em segundos para execução de comandos.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='videos.deviceconfigaudio')),
            ],
        ),
    ]
