# Generated by Django 6.0 on 2026-01-14 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoParaCalculoGravacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_hd_gb', models.FloatField(default=10, verbose_name='Tamanho do HD (GB)')),
                ('tamanho_video_mb', models.FloatField(default=13.1, verbose_name='Tamanho do Vídeo (MB)')),
                ('duracao_video_min', models.FloatField(default=10, verbose_name='Duração do Vídeo (min)')),
                ('hora_inicio', models.TimeField(default='08:30', verbose_name='Início da Gravação')),
                ('hora_fim', models.TimeField(default='20:00', verbose_name='Fim da Gravação')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(default='Dispositivo', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(choices=[('server', 'Server'), ('app', 'App'), ('server_ftp', 'Server_FTP')], help_text='Origem do erro: server ou app', max_length=10)),
                ('mensagem_erro', models.TextField(help_text='Descrição detalhada do erro')),
                ('data_erro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Erro',
                'verbose_name_plural': 'Logs de Erro',
                'ordering': ['-data_erro'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('error', 'Erro')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('file_Server', models.CharField(max_length=255, verbose_name='Nome do Arquivo no Servidor')),
                ('url_php_server', models.URLField(default='https://rcamgeo.com.br/api/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfigAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(help_text='Nome do arquivo ou string de configuração do áudio.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='videos.device', to_field='hostname')),
            ],
            options={
                'verbose_name': 'Áudio do dispositivo',
                'verbose_name_plural': 'Áudios dos dispositivos',
                'ordering': ['hostname', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompiledVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/compilados/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('source_videos', models.ManyToManyField(related_name='compiled_in', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('hostname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='videos.device', to_field='hostname')),
                ('tempo', models.PositiveIntegerField(default=10, help_text='Tempo em segundos para execução de comandos.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='videos.deviceconfigaudio')),
            ],
        ),
    ]
