# Generated by Django 6.0 on 2026-01-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='Thumbnail do Vídeo'),
        ),
    ]
