# Generated by Django 6.0 on 2025-12-08 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('hostname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='videos.device', to_field='hostname')),
                ('tempo', models.PositiveIntegerField(default=10, help_text='Tempo em segundos para execução de comandos.')),
                ('audio', models.CharField(blank=True, help_text='Nome do arquivo ou comando de áudio.', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
