# Generated by Django 6.0 on 2025-12-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompiledVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/compilados/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('source_videos', models.ManyToManyField(related_name='compiled_in', to='videos.video')),
            ],
        ),
    ]
