# Generated by Django 6.0 on 2025-12-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_compiledvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
