# Generated by Django 6.0 on 2025-12-08 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_deviceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='audio',
            field=models.CharField(blank=True, help_text='String de configuração de áudio.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DeviceConfigAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(help_text='Nome do arquivo ou string de configuração do áudio.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='videos.device', to_field='hostname')),
            ],
            options={
                'verbose_name': 'Áudio do dispositivo',
                'verbose_name_plural': 'Áudios dos dispositivos',
                'ordering': ['hostname', 'created_at'],
            },
        ),
    ]
