# Generated by Django 6.0 on 2025-12-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(choices=[('server', 'Server'), ('app', 'App')], help_text='Origem do erro: server ou app', max_length=10)),
                ('mensagem_erro', models.TextField(help_text='Descrição detalhada do erro')),
                ('data_erro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Erro',
                'verbose_name_plural': 'Logs de Erro',
                'ordering': ['-data_erro'],
            },
        ),
    ]
