# Generated by Django 6.0 on 2026-01-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
